<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>xpath</name>
   <tag></tag>
   <elementGuidId>24e6630b-9c71-4349-9af0-925dab266e8d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>${xpath}</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
